// Code generated by templ@v0.2.364 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func debug() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if err != nil {
			return err
		}
		var_2 := `Porto - Tailwind Template`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</title><link rel=\"stylesheet\" href=\"assets/new_output.css\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"{`https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&amp;display=swap`}\" rel=\"stylesheet\"><script src=\"https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js\" integrity=\"sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\">")
		if err != nil {
			return err
		}
		var_3 := ``
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</script></head><body class=\"bg-gray-100\"><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><nav class=\"flex items-center justify-between mb-40\"><img src=\"assets/image/navbar-logo.png\" alt=\"Logo\"><button class=\"px-7 py-3 md:px-9 md:py-4 bg-white font-medium md:font-semibold text-gray-700 text-md rounded-md hover:bg-gray-700 hover:text-white transition ease-linear duration-500\">")
		if err != nil {
			return err
		}
		var_4 := `Get my CV`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></nav><div class=\"text-center\"><div class=\"flex justify-center mb-16\"><img src=\"assets/image/home-img.png\" alt=\"Image\"></div><h6 class=\"font-medium text-gray-600 text-lg md:text-2xl uppercase mb-8\">")
		if err != nil {
			return err
		}
		var_5 := `Greg C.`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><h1 class=\"font-normal text-gray-900 text-4xl md:text-7xl leading-none mb-8\">")
		if err != nil {
			return err
		}
		var_6 := `Senior Backend Developer`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-600 text-md md:text-xl mb-16\">")
		if err != nil {
			return err
		}
		var_7 := `I have a passion for software. I enjoy creating tools that make life easier for people.`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><!--")
		if err != nil {
			return err
		}
		var_8 := `<a href="#" class="px-7 py-3 md:px-9 md:py-4 font-medium md:font-semibold bg-gray-700 text-gray-50 text-sm rounded-md hover:bg-gray-50 hover:text-gray-700 transition ease-linear duration-500">Hire me</a>`
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("--></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\"><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><div class=\"w-20 py-6 flex justify-center bg-gray-100 rounded-md mb-4\"><i data-feather=\"activity\"></i></div><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_9 := `High experience`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_10 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_10)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_11 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_12 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_12)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><div class=\"w-20 py-6 flex justify-center bg-gray-100 rounded-md mb-4\"><i data-feather=\"codesandbox\"></i></div><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_13 := `Useful sandboxes`
		_, err = templBuffer.WriteString(var_13)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_14 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_14)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_15 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_15)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_16 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_16)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><div class=\"w-20 py-6 flex justify-center bg-gray-100 rounded-md mb-4\"><i data-feather=\"coffee\"></i></div><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_17 := `Success side projects`
		_, err = templBuffer.WriteString(var_17)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_18 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_18)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_19 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_19)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_20 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_20)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><div class=\"flex flex-col lg:flex-row justify-between\"><div class=\"mb-10 lg:mb-0\"><h1 class=\"font-medium text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_21 := `Portfolio`
		_, err = templBuffer.WriteString(var_21)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-xs md:text-base\">")
		if err != nil {
			return err
		}
		var_22 := `I have brought here my biggest and favorite works as a professional.`
		_, err = templBuffer.WriteString(var_22)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div><div class=\"space-y-24\"><div class=\"flex space-x-6\"><h1 class=\"font-normal text-gray-700 text-3xl md:text-4xl\">")
		if err != nil {
			return err
		}
		var_23 := `01`
		_, err = templBuffer.WriteString(var_23)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><span class=\"w-28 h-0.5 bg-gray-300 mt-5\"></span><div><h1 class=\"font-normal text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_24 := `Demo API Generator`
		_, err = templBuffer.WriteString(var_24)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-sm md:text-base\">")
		if err != nil {
			return err
		}
		var_25 := `A dummy data free and documented API generator to facilitate `
		_, err = templBuffer.WriteString(var_25)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_26 := `the process of testing the front-end portion of projects.`
		_, err = templBuffer.WriteString(var_26)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div><div class=\"flex space-x-6\"><h1 class=\"font-normal text-gray-700 text-3xl md:text-4xl\">")
		if err != nil {
			return err
		}
		var_27 := `02`
		_, err = templBuffer.WriteString(var_27)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><span class=\"w-28 h-0.5 bg-gray-300 mt-5\"></span><div><h1 class=\"font-normal text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_28 := `Demo API Generator`
		_, err = templBuffer.WriteString(var_28)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-sm md:text-base\">")
		if err != nil {
			return err
		}
		var_29 := `A dummy data free and documented API generator to facilitate `
		_, err = templBuffer.WriteString(var_29)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_30 := `the process of testing the front-end portion of projects.`
		_, err = templBuffer.WriteString(var_30)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div><div class=\"flex space-x-6\"><h1 class=\"font-normal text-gray-700 text-3xl md:text-4xl\">")
		if err != nil {
			return err
		}
		var_31 := `03`
		_, err = templBuffer.WriteString(var_31)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><span class=\"w-28 h-0.5 bg-gray-300 mt-5\"></span><div><h1 class=\"font-normal text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_32 := `Demo API Generator`
		_, err = templBuffer.WriteString(var_32)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-sm md:text-base\">")
		if err != nil {
			return err
		}
		var_33 := `A dummy data free and documented API generator to facilitate `
		_, err = templBuffer.WriteString(var_33)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_34 := `the process of testing the front-end portion of projects.`
		_, err = templBuffer.WriteString(var_34)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div></div></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><h1 class=\"font-medium text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_35 := `Education`
		_, err = templBuffer.WriteString(var_35)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-xs md:text-base mb-20\">")
		if err != nil {
			return err
		}
		var_36 := `Below is a summary of the places I studied`
		_, err = templBuffer.WriteString(var_36)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\"><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_37 := `2015 – 2016`
		_, err = templBuffer.WriteString(var_37)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_38 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_38)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_39 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_39)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_40 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_40)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"relative\"><h6 class=\"font-semibold text-gray-500 text-md relative z-10\">")
		if err != nil {
			return err
		}
		var_41 := `See the place here`
		_, err = templBuffer.WriteString(var_41)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><span class=\"w-32 h-1 bg-blue-200 absolute bottom-1 left-0 z-0\"></span></div></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_42 := `2015 – 2016`
		_, err = templBuffer.WriteString(var_42)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_43 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_43)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_44 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_44)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_45 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_45)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"relative\"><h6 class=\"font-semibold text-gray-500 text-md relative z-10\">")
		if err != nil {
			return err
		}
		var_46 := `See the place here`
		_, err = templBuffer.WriteString(var_46)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><span class=\"w-32 h-1 bg-blue-200 absolute bottom-1 left-0 z-0\"></span></div></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_47 := `2015 – 2016`
		_, err = templBuffer.WriteString(var_47)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_48 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_48)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_49 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_49)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_50 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_50)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"relative\"><h6 class=\"font-semibold text-gray-500 text-md relative z-10\">")
		if err != nil {
			return err
		}
		var_51 := `See the place here`
		_, err = templBuffer.WriteString(var_51)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><span class=\"w-32 h-1 bg-blue-200 absolute bottom-1 left-0 z-0\"></span></div></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_52 := `2015 – 2016`
		_, err = templBuffer.WriteString(var_52)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_53 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_53)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_54 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_54)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_55 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_55)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"relative\"><h6 class=\"font-semibold text-gray-500 text-md relative z-10\">")
		if err != nil {
			return err
		}
		var_56 := `See the place here`
		_, err = templBuffer.WriteString(var_56)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><span class=\"w-32 h-1 bg-blue-200 absolute bottom-1 left-0 z-0\"></span></div></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_57 := `2015 – 2016`
		_, err = templBuffer.WriteString(var_57)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_58 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_58)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_59 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_59)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_60 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_60)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"relative\"><h6 class=\"font-semibold text-gray-500 text-md relative z-10\">")
		if err != nil {
			return err
		}
		var_61 := `See the place here`
		_, err = templBuffer.WriteString(var_61)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><span class=\"w-32 h-1 bg-blue-200 absolute bottom-1 left-0 z-0\"></span></div></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><h4 class=\"font-medium text-gray-700 text-lg mb-4\">")
		if err != nil {
			return err
		}
		var_62 := `2015 – 2016`
		_, err = templBuffer.WriteString(var_62)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h4><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_63 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_63)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_64 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_64)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_65 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_65)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"relative\"><h6 class=\"font-semibold text-gray-500 text-md relative z-10\">")
		if err != nil {
			return err
		}
		var_66 := `See the place here`
		_, err = templBuffer.WriteString(var_66)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><span class=\"w-32 h-1 bg-blue-200 absolute bottom-1 left-0 z-0\"></span></div></div></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><div class=\"text-center\"><h1 class=\"font-normal text-gray-300 text-3xl md:text-6xl lg:text-7xl mb-20 md:mb-32 lg:mb-48\">")
		if err != nil {
			return err
		}
		var_67 := `Please do not measure your skills in `
		_, err = templBuffer.WriteString(var_67)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_68 := `percentages!`
		_, err = templBuffer.WriteString(var_68)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-medium text-gray-700 text-xs md:text-base\">")
		if err != nil {
			return err
		}
		var_69 := `In my many years of experience, I use @laravel for backend projects and @vuejs for `
		_, err = templBuffer.WriteString(var_69)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_70 := `front-end projects. I’m an avid programmer, so I create designs based on the `
		_, err = templBuffer.WriteString(var_70)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_71 := `weekend @figmadesign.`
		_, err = templBuffer.WriteString(var_71)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><h1 class=\"font-medium text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_72 := `Experience`
		_, err = templBuffer.WriteString(var_72)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-xs md:text-base mb-20\">")
		if err != nil {
			return err
		}
		var_73 := `Below is a summary of the places I studied`
		_, err = templBuffer.WriteString(var_73)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"flex flex-col lg:flex-row justify-between\"><div class=\"space-y-8 md:space-y-16 mb-16 md:mb-0\"><h6 class=\"font-medium text-gray-400 text-base uppercase\">")
		if err != nil {
			return err
		}
		var_74 := `Company`
		_, err = templBuffer.WriteString(var_74)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><p class=\"font-semibold text-gray-600 text-base\">")
		if err != nil {
			return err
		}
		var_75 := `Massa Fames `
		_, err = templBuffer.WriteString(var_75)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-normal text-gray-300\">")
		if err != nil {
			return err
		}
		var_76 := `/ New York`
		_, err = templBuffer.WriteString(var_76)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></p><p class=\"font-semibold text-gray-600 text-base\">")
		if err != nil {
			return err
		}
		var_77 := `Massa Fames `
		_, err = templBuffer.WriteString(var_77)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-normal text-gray-300\">")
		if err != nil {
			return err
		}
		var_78 := `/ New York`
		_, err = templBuffer.WriteString(var_78)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></p><p class=\"font-semibold text-gray-600 text-base\">")
		if err != nil {
			return err
		}
		var_79 := `Massa Fames `
		_, err = templBuffer.WriteString(var_79)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-normal text-gray-300\">")
		if err != nil {
			return err
		}
		var_80 := `/ New York`
		_, err = templBuffer.WriteString(var_80)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></p><p class=\"font-semibold text-gray-600 text-base\">")
		if err != nil {
			return err
		}
		var_81 := `Massa Fames `
		_, err = templBuffer.WriteString(var_81)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-normal text-gray-300\">")
		if err != nil {
			return err
		}
		var_82 := `/ New York`
		_, err = templBuffer.WriteString(var_82)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></p><p class=\"font-semibold text-gray-600 text-base\">")
		if err != nil {
			return err
		}
		var_83 := `Massa Fames `
		_, err = templBuffer.WriteString(var_83)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-normal text-gray-300\">")
		if err != nil {
			return err
		}
		var_84 := `/ New York`
		_, err = templBuffer.WriteString(var_84)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></p></div><div class=\"space-y-8 md:space-y-16 mb-16 md:mb-0\"><h6 class=\"font-medium text-gray-400 text-base uppercase\">")
		if err != nil {
			return err
		}
		var_85 := `Position`
		_, err = templBuffer.WriteString(var_85)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_86 := `Junior Front-End Developer`
		_, err = templBuffer.WriteString(var_86)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_87 := `Junior Front-End Developer`
		_, err = templBuffer.WriteString(var_87)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_88 := `Junior Front-End Developer`
		_, err = templBuffer.WriteString(var_88)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_89 := `Junior Front-End Developer`
		_, err = templBuffer.WriteString(var_89)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_90 := `Junior Front-End Developer`
		_, err = templBuffer.WriteString(var_90)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div><div class=\"space-y-8 md:space-y-16\"><h6 class=\"font-medium text-gray-400 text-base uppercase\">")
		if err != nil {
			return err
		}
		var_91 := `Year`
		_, err = templBuffer.WriteString(var_91)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h6><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_92 := `2016`
		_, err = templBuffer.WriteString(var_92)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_93 := `2016`
		_, err = templBuffer.WriteString(var_93)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_94 := `2016`
		_, err = templBuffer.WriteString(var_94)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_95 := `2016`
		_, err = templBuffer.WriteString(var_95)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><p class=\"font-normal text-gray-400 text-base\">")
		if err != nil {
			return err
		}
		var_96 := `2016`
		_, err = templBuffer.WriteString(var_96)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><h1 class=\"font-medium text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_97 := `Brands`
		_, err = templBuffer.WriteString(var_97)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-xs md:text-base mb-10 md:mb-20\">")
		if err != nil {
			return err
		}
		var_98 := `Below is a summary of the places I studied`
		_, err = templBuffer.WriteString(var_98)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3\"><img src=\"assets/image/brand-1.png\" alt=\"Image\"><img src=\"assets/image/brand-2.png\" alt=\"Image\"><img src=\"assets/image/brand-3.png\" alt=\"Image\"><img src=\"assets/image/brand-4.png\" alt=\"Image\"><img src=\"assets/image/brand-5.png\" alt=\"Image\"><img src=\"assets/image/brand-6.png\" alt=\"Image\"></div></div></section><section class=\"py-10 md:py-16\"><div class=\"container max-w-screen-xl mx-auto px-4\"><h1 class=\"font-medium text-gray-700 text-3xl md:text-4xl mb-5\">")
		if err != nil {
			return err
		}
		var_99 := `Testimonial`
		_, err = templBuffer.WriteString(var_99)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-500 text-xs md:text-base mb-10 md:mb-20\">")
		if err != nil {
			return err
		}
		var_100 := `Below is a summary of the places I studied`
		_, err = templBuffer.WriteString(var_100)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\"><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_101 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_101)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_102 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_102)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_103 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_103)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><h6 class=\"font-semibold text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_104 := `Stephan Clark `
		_, err = templBuffer.WriteString(var_104)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-medium text-gray-300 text-sm\">")
		if err != nil {
			return err
		}
		var_105 := `- CEO at EarlyBird`
		_, err = templBuffer.WriteString(var_105)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></h6></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_106 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_106)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_107 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_107)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_108 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_108)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><h6 class=\"font-semibold text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_109 := `Stephan Clark `
		_, err = templBuffer.WriteString(var_109)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-medium text-gray-300 text-sm\">")
		if err != nil {
			return err
		}
		var_110 := `- CEO at EarlyBird`
		_, err = templBuffer.WriteString(var_110)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></h6></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_111 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_111)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_112 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_112)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_113 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_113)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><h6 class=\"font-semibold text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_114 := `Stephan Clark `
		_, err = templBuffer.WriteString(var_114)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-medium text-gray-300 text-sm\">")
		if err != nil {
			return err
		}
		var_115 := `- CEO at EarlyBird`
		_, err = templBuffer.WriteString(var_115)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></h6></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_116 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_116)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_117 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_117)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_118 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_118)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><h6 class=\"font-semibold text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_119 := `Stephan Clark `
		_, err = templBuffer.WriteString(var_119)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-medium text-gray-300 text-sm\">")
		if err != nil {
			return err
		}
		var_120 := `- CEO at EarlyBird`
		_, err = templBuffer.WriteString(var_120)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></h6></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_121 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_121)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_122 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_122)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_123 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_123)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><h6 class=\"font-semibold text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_124 := `Stephan Clark `
		_, err = templBuffer.WriteString(var_124)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-medium text-gray-300 text-sm\">")
		if err != nil {
			return err
		}
		var_125 := `- CEO at EarlyBird`
		_, err = templBuffer.WriteString(var_125)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></h6></div><div class=\"bg-gray-50 px-8 py-10 rounded-md\"><p class=\"font-normal text-gray-500 text-md mb-4\">")
		if err != nil {
			return err
		}
		var_126 := `Lorem ipsum dolor sit amet, consectetur `
		_, err = templBuffer.WriteString(var_126)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_127 := `adipiscing elit, sed do eiusmod tempor `
		_, err = templBuffer.WriteString(var_127)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_128 := `incididunt ut labore et dolore magna aliqua.`
		_, err = templBuffer.WriteString(var_128)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><h6 class=\"font-semibold text-gray-500 text-md\">")
		if err != nil {
			return err
		}
		var_129 := `Stephan Clark `
		_, err = templBuffer.WriteString(var_129)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<span class=\"font-medium text-gray-300 text-sm\">")
		if err != nil {
			return err
		}
		var_130 := `- CEO at EarlyBird`
		_, err = templBuffer.WriteString(var_130)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span></h6></div></div></div></section><footer class=\"py-10 md:py-16 mb-20 md:mb-40 lg::mb-52\"><div class=\"container max-w-screen-xl mx-auto px-4\"><div class=\"text-center\"><h1 class=\"font-medium text-gray-700 text-4xl md:text-5xl mb-5\">")
		if err != nil {
			return err
		}
		var_131 := `Testimonial`
		_, err = templBuffer.WriteString(var_131)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><p class=\"font-normal text-gray-400 text-md md:text-lg mb-20\">")
		if err != nil {
			return err
		}
		var_132 := `I’m not currently taking on new client work but feel free to contact me for any `
		_, err = templBuffer.WriteString(var_132)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<br> ")
		if err != nil {
			return err
		}
		var_133 := `other inquiries.`
		_, err = templBuffer.WriteString(var_133)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p><div class=\"flex items-center justify-center space-x-8\"><a href=\"#\" class=\"w-16 h-16 flex items-center justify-center rounded-full hover:bg-gray-200 transition ease-in-out duration-500\"><i data-feather=\"twitter\" class=\"text-gray-500 hover:text-gray-800 transition ease-in-out duration-500\"></i></a><a href=\"#\" class=\"w-16 h-16 flex items-center justify-center rounded-full hover:bg-gray-200 transition ease-in-out duration-500\"><i data-feather=\"dribbble\" class=\"text-gray-500 hover:text-gray-700 transition ease-in-out duration-500\"></i></a><a href=\"#\" class=\"w-16 h-16 flex items-center justify-center rounded-full hover:bg-gray-200 transition ease-in-out duration-500\"><i data-feather=\"facebook\" class=\"text-gray-500 hover:text-gray-700 transition ease-in-out duration-500\"></i></a><a href=\"#\" class=\"w-16 h-16 flex items-center justify-center rounded-full hover:bg-gray-200 transition ease-in-out duration-500\"><i data-feather=\"codepen\" class=\"text-gray-500 hover:text-gray-700 transition ease-in-out duration-500\"></i></a><a href=\"#\" class=\"w-16 h-16 flex items-center justify-center rounded-full hover:bg-gray-200 transition ease-in-out duration-500\"><i data-feather=\"at-sign\" class=\"text-gray-500 hover:text-gray-700 transition ease-in-out duration-500\"></i></a><a href=\"#\" class=\"w-16 h-16 flex items-center justify-center rounded-full hover:bg-gray-200 transition ease-in-out duration-500\"><i data-feather=\"instagram\" class=\"text-gray-500 hover:text-gray-700 transition ease-in-out duration-500\"></i></a></div></div></div></footer><script>")
		if err != nil {
			return err
		}
		var_134 := `
            feather.replace()
        `
		_, err = templBuffer.WriteString(var_134)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</script></body></html>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
