// Code generated by templ@v0.2.364 DO NOT EDIT.

package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func home() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<html>")
		if err != nil {
			return err
		}
		err = headerComponent("Greg C. 👨‍💻 ✈️ ⚽").Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<body class=\"bg-gray-100\"><div class=\"flex justify-center items-center min-h-screen\"><div class=\"max-w-4xl bg-white shadow-lg rounded-lg overflow-hidden\"><div class=\"md:flex \"><div class=\"p-8\"><a href=\"#\" class=\"block mt-1  leading-tight font-medium text-black hover:underline\">")
		if err != nil {
			return err
		}
		var_2 := `Greg C.`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a><p class=\"mt-2 text-gray-600 text-lg\">")
		if err != nil {
			return err
		}
		var_3 := `A software developer, fpv drone pilot, self-hosted software enthusiast - based in Christchurch, New Zealand (GMT+13 )`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div><div class=\"p-4\"><div class=\"mt-2\">")
		if err != nil {
			return err
		}
		var var_4 string = "{ Open to new software development opportunities. I thrive in fast-paced, high trust environments, with a clear path to having a big impact and everyone moving in the same direction. Only considering fully/largely remote roles.} "
		_, err = templBuffer.WriteString(templ.EscapeString(var_4))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></div><a class=\"block p-4 bg-white rounded-lg shadow hover:shadow-md transition duration-300 ease-in-out\" href=\"#about\"><h3 class=\"text-center text-xl font-medium\">")
		if err != nil {
			return err
		}
		var_5 := `About`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h3></a><div class=\"px-4 pt-4 pb-2\"><div class=\"mt-2 grid grid-cols-3 sm:grid-cols-2 gap-4\"><a class=\"block p-4 bg-white rounded-lg shadow hover:shadow-md transition duration-300 ease-in-out\" href=\"#nzcovidmap\"><img src=\"/assets/covid19/icon-512x512.webp\" alt=\"Locations of Interest Explorer Icon\" class=\"h-16 w-16 md:h-24 md:w-24 mx-auto\"><h3 class=\"mt-2 text-center text-xl font-medium\">")
		if err != nil {
			return err
		}
		var_6 := `NZCovidMap`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h3></a><a class=\"block p-4 bg-white rounded-lg shadow hover:shadow-md transition duration-300 ease-in-out\" href=\"https://chch-water-reporter.vercel.app/\" target=\"_blank\"><img src=\"/assets/covid19/icon-512x512.png\" alt=\"Chch Water Reporter\" class=\"h-16 w-16 md:h-24 md:w-24 mx-auto\"><h3 class=\"mt-2 text-center text-xl font-medium\">")
		if err != nil {
			return err
		}
		var_7 := `Chch Water Reporter`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h3></a><a class=\"block p-4 bg-white rounded-lg shadow hover:shadow-md transition duration-300 ease-in-out\" href=\"https://label-maker-3000.fly.dev\" target=\"_blank\"><img src=\"/assets/covid19/icon-512x512.png\" alt=\"Locations of Interest Explorer Icon\" class=\"h-16 w-16 md:h-24 md:w-24 mx-auto\"><h3 class=\"mt-2 text-center text-xl font-medium\">")
		if err != nil {
			return err
		}
		var_8 := `Label-Maker-3000 (wip)`
		_, err = templBuffer.WriteString(var_8)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h3></a></div></div></div></div>")
		if err != nil {
			return err
		}
		err = aboutPage().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = nzCovidMap().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = chchWaterReporter().Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</body></html>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
